version: '3'
services:
  postgres:
    image: postgres:16-alpine3.20
    environment:
      POSTGRES_DB: hw02
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build: .
    image: hw02
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/hw02
    ports:
      - "80:8000"
    depends_on:
      - postgres
